name: CI

on:
  push:
    branches: [ main, task-* ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pandas numpy matplotlib scipy scikit-learn
        pip install -r requirements.txt
        
    - name: Create directories
      run: |
        mkdir -p data/processed
        mkdir -p results/figures
        
    - name: Run tests
      run: |
        python -m pytest tests/ -v --tb=short
        
    - name: Code quality check
      run: |
        pip install flake8
        flake8 src/ --max-line-length=120 --ignore=E501,W503,W293,F401,E226,W504,F541,W291,E231,E303 --count || true